### ISSUE TITLE
ArduCopter Needs an emergency shut-down function

### ISSUE THREAD

**Issue by lordneeko** [SkyRocketToys/ardupilot#20]
#### Issue details
The Skyviper quads have the bad habit of burning out motors if a prop gets tangled or caught. The problem is that the copter (whether is auto or manual) doesn't have a function to make the copter completely turn off the motors. So if you have a bad landing in high grass, the props will get tangled, but the motors will still run for a few (10-15) seconds which can cause them to burn out. Recommend programming an emergency shut-off function then linking that to a button combo on the controllers.

#### Version
v2450HD (latest firmware)

#### Platform
[  ] All
[  ] AntennaTracker
[X ] Copter
[  ] Plane
[  ] Rover

#### Airframe type
quadcopter

#### Hardware type
?

#### Logs
_Please provide a link to any relevant logs that show the issue_

**Comment by MattMSRT** [comment]
Hi Lordneeko, 

There is a function for that already. It's been in place since day 1. It's a quick tap/press of the power button. That will instantly kill the motors without turning off the TX. The TX turns off with a LONG press of the power button. 

There is also obstruction code in the FW that can help detect scenarios that can damage brushed motors, but due to the nature of brushed motors, there can be performance issues even after 2 seconds of obstruction. 

Thanks,
Matt

**Comment by lordneeko** [comment]
Thanks I didn't realize that. Closed.
